### PR TITLE
Create Siphon_XRAY_Cartopy_HRRR.ipynb

### PR DESCRIPTION
**Pull request by rsignell-usgs**
Example of using Siphon to extract data from HRRR, Xray to read the extracted file, and Cartopy to plot up the Lambert Conformal Conic data

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Don't want this notebook?

**Comment by dopplershift** [comment]
I wasn't planning to merge until we put xray on the actual workshop plan for the next round.

However, that planning would be 12 months from now.....so I'll go ahead and merge.  Thanks!

**Comment by rsignell-usgs** [comment]
@dopplershift, thanks!
BTW, what exactly is http://thredds-jumbo.unidata.ucar.edu/thredds/catalog.html and is it stable enough to use in notebooks we distribute to others?

**Comment by dopplershift** [comment]
thredds-jumbo is where we put our bigger "operational" datasets that won't
fit on the regular server.

On Mon, Aug 24, 2015 at 2:36 PM, Rich Signell <notifications@github.com>
wrote:

> @dopplershift <https://github.com/dopplershift>, thanks!
> BTW, what exactly is
> http://thredds-jumbo.unidata.ucar.edu/thredds/catalog.html and is it
> stable enough to use in notebooks we distribute to others?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/unidata-python-workshop/pull/52#issuecomment-134371802>
> .
>



-- 
Ryan May
Software Engineer
UCAR/Unidata
Boulder, CO

**Pull request merged**
