### PR TITLE
Use XVFB for headless testing of scripts

### PR DESCRIPTION
**Pull request by jrleeman**
Headless testing of the scripts are failing on Travis again - use xvfb to get around this.

### CODE REVIEW

**Comment by jrleeman** [comment]
This will have to merge before the other PR's I'm opening today.

**Comment by dopplershift** [comment]
Looks like `DISPLAY` is still complaining on Linux...

**Comment by jrleeman** [comment]
Wonderful - I'll have to see what's going on here.

**Comment by jrleeman** [comment]
Ready to merge? Then I will rebase the other PR's on this.

**Pull request merged**
