### PR TITLE
Revise Upper Air Tutorial

### PR DESCRIPTION
**Pull request by jrleeman**
Dressed up header and split up with more exercises. A few things:

- [x] Add CAPE and CIN when they are implemented
- [x] Modify figure aspect ratio
- [x] See if we have the iastate read fixed or remove it

### CODE REVIEW

**Comment by jrleeman** [comment]
Need to update once we merge changes in MetPy

**Comment by jrleeman** [comment]
I think this is ready for a look-over and see if we want to add/remove anything.

**Comment by jrleeman** [comment]
1 & 2 - Agreed
3 - Looks like our LFC calculation can get borked in this situation when there is a setup like this... looking into it
4 - Don't know if that's how it'll wash out. We can put that down and adjust after running it
5 - Greater than 100? I suppose, but not following the need.

**Comment by dopplershift** [comment]
That hodograph doesn't look right, especially for a supercell day. I'm guessing that's because the stratospheric winds are turning back.

**Comment by jrleeman** [comment]
On this hodograph wind thing. Should we mask it in the notebook, or should we add a `max_altitude` functionality to the hodograph?

**Comment by dopplershift** [comment]
Let's mask in the notebook for now until we decide that's the API we want on `hodograph`.

**Comment by jrleeman** [comment]
Should be good to go now as well.

**Comment by jrleeman** [comment]
Ready to merge if you're happy with the content @dopplershift

**Pull request merged**
