### PR TITLE
Notebook headers

### PR DESCRIPTION
**Pull request by jrleeman**
Add notebook headers and images to all notebooks for a uniform look. We can still improve by adding time estimates and objectives to everything, but this at least gets us a uniform appearance.

### CODE REVIEW

**Comment by dopplershift** [comment]
So long as the Jupyter examples are taken from the Jupyter folks, I don't feel good adding our header.

**Comment by jrleeman** [comment]
I didn't know you pulled from them. Just the ones in that directory?

**Comment by dopplershift** [comment]
Yeah, that's all.

**Comment by jrleeman** [comment]
Done - be sure to checkout the siphon radar and troubleshooting notebooks.

**Comment by dopplershift** [comment]
I think we can ignore the AppVeyor failures. Love the images for Siphon and troubleshooting.

**Pull request merged**
