### PR TITLE
Build maintenance

### LINKED ISSUE #223: Automatically test solutions implemented with `%load` magic
Adding solutions to exercises with the `%load` magic is great... except when it comes to testing those solutions. The line with the magic needs to be uncommented and the cell run to load the solution, then the cell needs to be run again to actually evaluate the solution. If we don't test our solutions, they will surely break. From what I can tell there isn't an easy way to do this with any sort of existing pre processor. Here's the approach I'm thinking is best:

1) Look through the notebook files and find cells with a load magic with a regex like: `"#\s?%load.*"`
2) Go grab the content of that file
3) Reformat that file content to be json for the notebook cell
4) Replace the content in that cell with the content from the file
5) Save that notebook
6) Run it as normal in the testing matrix

There is a magic cell tagging preprocessor http://nbconvert.readthedocs.io/en/latest/api/preprocessors.html, but it doesn't seem to have the functionality we need.

### PR DESCRIPTION
**Pull request by jrleeman**
Addresses #230 and gets things green again. Still two outliers I'm working on, but wanted to get Travis going on it. Will also close #223 and #156.

### CODE REVIEW

**Comment by jrleeman** [comment]
The notebooks currently failing are due to surface data, radar data, and generally remote data issues. Do we want to blacklist them from tests, merge, then re list them as we rework the material? Especially since they will largely be blasted I believe. @dopplershift

**Comment by dopplershift** [comment]
Black list them by moving them to a directory that makes it clear they're not working. I don't want to forget to fix them.

**Comment by jrleeman** [comment]
It's green! Anything else we want to do mnt wise @dopplershift ?

**Comment by dopplershift** [comment]
I'm sure there is, but it can be another PR.

**Pull request merged**
