### PR TITLE
GOES-16 RGB

### PR DESCRIPTION
**Pull request by jrleeman**
Show students how to use numpy and a bit of basic image processing to create an RGB image from GOES-16 data.

### CODE REVIEW

**Comment by jrleeman** [comment]
Need to add text and cleanup still, but the basic images are made.

**Comment by dopplershift** [comment]
I think this needs a rebase to remove the first commit.

**Comment by dopplershift** [comment]
Need to increase the CI timeouts in order to run this notebook.

**Comment by jrleeman** [comment]
I set the timeout to 15, but looks like CI limits to 10 internally....

**Comment by dopplershift** [comment]
I guess you could add it to a subdir, since those aren't picked up at the moment.

Or subset the data more.

**Pull request merged**
