### PR TITLE
Build maintenance

### PR DESCRIPTION
**Pull request by jrleeman**
More build fun - hopefully we can finally get green and be ready for a workshop.

### CODE REVIEW

**Comment by dopplershift** [comment]
Why the change to drop units? The matplotlib converter should be automatically activated and working. If that's not the case, we need to fix MetPy.

**Comment by jrleeman** [comment]
You have temperature and windspeed plotting on the same axis. Matplotlib doesn't grock that apparently as it attempts to convert them to a common unit.

**Comment by dopplershift** [comment]
Can we use dew point instead? I'm not exactly wild about teaching with an example that I wouldn't actually advocate in reality.

**Comment by jrleeman** [comment]
You've got windspeed tied in throughout, but that notebook should be on the slash and burn list anyway as it's mostly pre the first slash and burn.

**Comment by dopplershift** [comment]
Ah, ok. Carry on then.

**Comment by jrleeman** [comment]
GREEN!

**Pull request merged**
