### PR TITLE
Retool for GOES-16 imagery

### PR DESCRIPTION
**Pull request by jrleeman**
Reworked the satellite tutorial to use GOES-16 imagery. Still using a mid-level WV channel. A few differences from the GINI tutorial:

* No coordinates attribute in data variable
* No time attribute
* Most recent data is last element as opposed to first

You can see how I handled it in the notebook. I have reworded the explanations as well. Working on a RGB notebook next, but I think it will be a separate PR and notebook to go through time permitting.

### CODE REVIEW

**Comment by jrleeman** [comment]
1. No problem
2. This points to a need for doc work - The docstring doesn't really describe what's going on. Seems more useful to specify max and min values, not a min and step?

**Comment by dopplershift** [comment]
Start and step are needed because it finds the range appropriate to the number of colors in the table. That's the point of using those functions anyways, for people who are used to GEMPAK-style tables.

**Comment by jrleeman** [comment]
Got it - I ended up setting the minimum to be a bit below our desired range and adjusted the step so it comes out to about 255 at the top end. Seems like having a min/max option would be useful though?

**Comment by jrleeman** [comment]
I think I'm done with this one too!

**Comment by jrleeman** [comment]
You get text dumps of the bin edges without it :/

**Comment by dopplershift** [comment]
Try ending the line with a `;`.

**Comment by jrleeman** [comment]
That works too - it just felt MATLAB-ey.. Fine with it if you are.

**Comment by dopplershift** [comment]
Let's go with it--only because I think you can escape without needing to explain it, whereas `_` is just too visible.

**Pull request merged**
