### PR TITLE
Add MetPy Case Study

### PR DESCRIPTION
**Pull request by kgoebber**
This PR adds the notebook for the MetPy Case Study from my forked repo of the workshop.

### CODE REVIEW

**Comment by dopplershift** [comment]
Are you ready for me to merge this? The test failures don't look related.

**Comment by kgoebber** [comment]
Not yet. This is the completed solution...I want to remove some of it for some live coding during this part of the course. I should have time to finish that up this week.

**Comment by jrleeman** [comment]
Are you planning to do it with load magics like we moved to in the workshop materials?

**Comment by jrleeman** [comment]
Ready to merge now that solutions are there?

**Comment by kgoebber** [comment]
Yeah, I think so. May need some refactor once the latest MetPy version is out, but I consider this complete.

**Comment by jrleeman** [comment]
Yeah, I figure we'll be doing some mods before we teach, but I'll go ahead and merge.

**Pull request merged**
