### PR TITLE
Fix syntax errors and height issue in plotting example.

### PR DESCRIPTION
**Pull request by jrleeman**
Fixes some issues found with the example during the Millersville workshop.

### CODE REVIEW

**Comment by dopplershift** [comment]
Can we add something (in travis/appveyor config, or in the notebook runner) to just run your script? That would certainly keep syntax errors from popping up in the future.

**Comment by jrleeman** [comment]
Probably - if we run it with all of the options it should be relatively thorough coverage. I'll see about adding it to the build.

**Comment by dopplershift** [comment]
Syntax errors are caught while it parses the file, so even importing, running it is enough to catch syntax errors *anywhere*.

Running it usefully expands it to catch some run-time problems.

**Comment by jrleeman** [comment]
Pending review this is good to go.

**Pull request merged**
