### PR TITLE
Add about notebooks

### PR DESCRIPTION
**Pull request by jrleeman**
I ran swiftly with the sharp knife of `git rebase` and came out bleeding. I will just create a new PR instead of salvaging #267 - Sorry about that @brianmapes

For the graphical representation:

### CODE REVIEW

**Comment by brianmapes** [comment]
Har har.

There’s always a way back, right?


On Mar 19, 2018, at 6:24 PM, John Leeman <notifications@github.com<mailto:notifications@github.com>> wrote:


I ran swiftly with the sharp knife of git rebase and came out bleeding. I will just create a new PR instead of salvaging #267<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F267&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=Z027Csanv9Bh4%2BNFPGhxWtNgnvXNlhGZ33nD7mLg17k%3D&reserved=0> - Sorry about that @brianmapes<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianmapes&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=M1PwlsxYwa4vu2zi%2Fo0EEEHhMgGkp%2BT7CkWJI%2BezgI4%3D&reserved=0>

For the graphical representation:
[https://camo.githubusercontent.com/24da4a4380ccf85fa74ef3fdd951cc2e14f1f209/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f324b643068715846697757756b2f67697068792e676966]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2F24da4a4380ccf85fa74ef3fdd951cc2e14f1f209%2F68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f324b643068715846697757756b2f67697068792e676966&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=r3A64QX7CV4MZIIIhUrs1jNl%2BEq9DnNiUj9VrkTPc1o%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Unidata/unidata-python-workshop/pull/276<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=DfkYYWm2C2FxK5nPG0UZQZQNFH%2ByF7HHpynDx%2FlqVRI%3D&reserved=0>

Commit Summary

  *   xarray not xray
  *   gitignore changed
  *   Create ABOUT_THESE_NOTEBOOKS.md
  *   Update .gitignore

File Changes

  *   M ideas.md<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276%2Ffiles%23diff-0&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=emlUzQMCTQa%2BqmmdoWgaEeSWZR6EOU55fOf9T1ZEur8%3D&reserved=0> (2)
  *   A notebooks/ABOUT_THESE_NOTEBOOKS.md<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276%2Ffiles%23diff-1&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=%2FP%2BekXuWv%2BdIHr1rBvrARjrK5sx0mOMibtuQ%2Bi%2F9hUc%3D&reserved=0> (62)

Patch Links:

  *   https://github.com/Unidata/unidata-python-workshop/pull/276.patch<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276.patch&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=tHBe7%2F0DOYphjlDSTTfKqIRtzRkec6xdFwQu5PU0%2BTI%3D&reserved=0>
  *   https://github.com/Unidata/unidata-python-workshop/pull/276.diff<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276.diff&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=FQ5CeG13nf3A27I4KtOQxOkO%2FQmQcv0hgqurBguBy6Q%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Funidata-python-workshop%2Fpull%2F276&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=DfkYYWm2C2FxK5nPG0UZQZQNFH%2ByF7HHpynDx%2FlqVRI%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB_VQpSavPfPHj5pzFffuoTpkE7sujBYks5tgDA3gaJpZM4SxALr&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C1bd6c68bbe9e4b11bab708d58de83e80%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636570950979780941&sdata=JfS0cF21Hwv1WRpFGHjlJwCtOC4U1esk2%2FUHBrBviL8%3D&reserved=0>.

*********************************************
Brian Mapes, Professor
Department of Atmospheric Sciences
Meteorology and Physical Oceanography Program
RSMAS, University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149-1031

phone: (305) 421-4275
fax: (305) 421-4696
email: mapes@miami.edu<mailto:mapes@miami.edu>
Web: http://www.rsmas.miami.edu/users/bmapes/
**********************************************

**Comment by jrleeman** [comment]
There is a way back, but in this case it's not pretty and I don't want to push to your master unnecessarily 😄

**Comment by brianmapes** [comment]
So, wait, one can push to a fork? Or only one who has made a pull request? Or what?

Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Mar 19, 2018, at 9:01 PM, John Leeman <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a way back, but in this case it's not pretty and I don't want to push to your master unnecessarily 😄

**Comment by dopplershift** [comment]
While your Pull Request is open, so long as you have the "Allow edits from maintainers" box on the right checked, we can push to the branch you used for the Pull Request. Once the Pull Request is merged, we can't push.

**Comment by jrleeman** [comment]
Just rebased, should be good pending CI.

**Pull request merged**
