### PR TITLE
Interactive GOES data exploration example

### PR DESCRIPTION
**Pull request by jrleeman**
Not ready to merge yet, but I wanted to throw this up. Since people really liked widgets at Millersville, should we try to employ them more in the workshop? This seemed like a fun way to poke around the GOES data.

### CODE REVIEW

**Comment by dopplershift** [comment]
In an ideal world, we could use this as the widgets example in the notebook. We're not there yet in the MetPy plotting helpers yet, though.

**Comment by jrleeman** [comment]
Thoughts on if we should show this at the Oklahoma workshop?

**Comment by dopplershift** [comment]
Nice to have around if we have the time--but I wouldn't count on having the time.

**Comment by jrleeman** [comment]
Have a look and see what you think of the notebook structure. Seems to be working reliably at this point.

**Comment by jrleeman** [comment]
Assuming the updates look good to you, this is good to go as well.

**Pull request merged**
