### PR TITLE
Add command line tool episode

### PR DESCRIPTION
**Pull request by jrleeman**
Add a lesson on how to combine the various skills learned during the workshop to make a simple, but useful command line tool.

### CODE REVIEW

**Comment by jrleeman** [comment]
I tried to write a simple tool that makes this kind of plot. I attempted to walk the line between following strict documentation practice vs. good practice that we'd like to see in a scientist's scripts. Curious how that went in the view of others. I wish the GFS had finer time steps when going back in time through the initialization. I'm planning on adding a brief into about command line tools in general and argparse. Maybe slides? A notebook? Hard to demo argument parsing without working with a script and the command line.p

figure_1

**Comment by dopplershift** [comment]
To demo, you could just parse in the arguments...
```python
parser.parse_args('--foo a --bar b'.split())
```

**Comment by jrleeman** [comment]
Then we don't get any of the help messages, etc though correct?

**Comment by jrleeman** [comment]
Any other thoughts or is this ready to rock?

**Comment by jrleeman** [comment]
I think this is good to go as well.

**Pull request merged**
