### PR TITLE
Add 10 mintues to conda slides

### PR DESCRIPTION
**Pull request by jrleeman**
Add the requested slides from the AMS 2018 short course.

### CODE REVIEW

**Comment by brianmapes** [comment]
That's helpful, but where is the presentation for setup? I want to replicate the short course lesson on Cartopy for a quick success. 

This one ends with "let's get your system set up" but I can't find the next thing. 

I see the instructions https://unidata.github.io/unidata-python-workshop/installation.html,  but that doesn't actually have what we used. 

Where  is  the "powershell" for windows users stuff for instance? Am I missing something? 
 
I need it for class tomorrow, where I hope to get 12 people installed and running.

**Comment by brianmapes** [comment]
That's helpful, but where is the presentation for setup? I want to replicate the short course lesson on Cartopy for a quick success.

This one ends with "let's get your system set up" but I can't find the next thing.

I see the instructions https://unidata.github.io/unidata-python-workshop/installation.html, but that doesn't actually have what we used.

Where is the "powershell" for windows users stuff for instance? Am I missing something?

I need it for class tomorrow, where I hope to get 12 people installed and running.



________________________________

**Comment by dopplershift** [comment]
(deleted duplicate)
Do you mean the one "slide" that had the link to the zip file and where to download anaconda?

**Comment by dopplershift** [comment]
@brianmapes Here's the instructions that we had on the screen when people came in:

1. Go to: https://github.com/Unidata/unidata-python-workshop
2. Click “Clone or Download” and download the zip file
3. If you don’t already have Anaconda or Miniconda, go to: https://conda.io/miniconda.html
4. Download Miniconda3 for your platform.

As far as "powershell" goes, on windows you get that by clicking "Anaconda Prompt" in the windows start menu.

**Comment by brianmapes** [comment]
Never mind. I had Success on a PC using native "Command Prompt", just from your steps on the installation page.


 I thought it sounded in the short course like like there were more PC challenges, this powershell thing. But this worked for me.  All set I hope.


https://github.com/MPO624/2018/blob/master/INITIAL_SETUP.md

[https://avatars0.githubusercontent.com/u/35411975?s=400&v=4]<https://github.com/MPO624/2018/blob/master/INITIAL_SETUP.md>

MPO624/2018<https://github.com/MPO624/2018/blob/master/INITIAL_SETUP.md>
github.com
MPO 624 CLASS FOR SPRING 2018




________________________________

**Comment by dopplershift** [comment]
That's good to know.

**Pull request merged**
